# Artillery configuration for performance testing of rooms_manager.cjs
config:
  target: "http://localhost:4000"
  phases:
    - duration: 60
      arrivalRate: 50
scenarios:
  - flow:
      - get:
          url: "/Room"
      - post:
          url: "/updateRooms"
          json:
            room_id: 1
            status: false