# Artillery configuration for performance testing
config:
  target: "http://localhost:3500"
  phases:
    - duration: 60
      arrivalRate: 50
scenarios:
  - flow:
      - post:
          url: "/scheduleMeeting"
          json:
            start_time: "2025-04-18T10:00:00Z"
            end_time: "2025-04-18T11:00:00Z"
      - post:
          url: "/joinMeetingNow"
          json:
            meeting_id: 1